# Generated by Django 5.0.3 on 2024-03-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finder',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='searcher',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
