# Generated by Django 5.0.3 on 2024-03-24 01:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_finder_name_searcher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finder',
            name='pet_type',
            field=models.CharField(default='cat', max_length=40),
        ),
        migrations.AddField(
            model_name='searcher',
            name='pet_type',
            field=models.CharField(default='cat', max_length=40),
        ),
        migrations.CreateModel(
            name='FinderEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('embedding', models.CharField(max_length=30000)),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.searcher')),
            ],
        ),
        migrations.CreateModel(
            name='SearcherEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('embedding', models.CharField(max_length=30000)),
                ('searcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.searcher')),
            ],
        ),
    ]
